import assert from 'node:assert/strict';
import { BASE_URL, blockExternal, launchBrowser } from './browser/_helpers.mjs';
const browser = await launchBrowser();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.setDefaultTimeout(10000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));await blockExternal(page);
try {
  for (const width of [1440,768,390]) {
    await page.setViewportSize({width,height:1000});
    for (const tab of ['overview','agents','mandates','payments','assistant','settings']) {
      await page.goto(`${BASE_URL}/test/fixtures/dashboard-harness.html?tab=${tab}`);
      await page.locator('h1').waitFor();
      await page.waitForTimeout(150);
      assert.equal(await page.locator('h1').evaluate(el=>getComputedStyle(el).fontSize),'28px',`${tab}: consistent page heading`);
      assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${tab}: overflow at ${width}`);
      await page.screenshot({path:`/tmp/chainpay-owner-${tab}-${width}.png`,fullPage:true});
    }
  }
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(`${BASE_URL}/test/fixtures/dashboard-harness.html?tab=payments`);
  assert.equal(await page.getByRole('button',{name:'Approve payment',exact:true}).count(),0,'history does not start a payment');
  await page.getByRole('button',{name:'New payment',exact:true}).click();
  await page.getByRole('button',{name:'Back to payments',exact:true}).click();
  await page.goto(`${BASE_URL}/test/fixtures/dashboard-harness.html?tab=assistant`);
  await page.getByRole('tab',{name:'Completed',exact:true}).click();
  await page.getByRole('tab',{name:'Needs attention',exact:true}).click();
  await page.getByRole('button',{name:'New request',exact:true}).click();
  await page.getByRole('textbox',{name:'Request',exact:true}).fill('Draft invoice request');
  await page.getByRole('button',{name:'Close composer'}).click();
  await page.getByRole('button',{name:'New request',exact:true}).click();
  assert.equal(await page.getByRole('textbox',{name:'Request',exact:true}).inputValue(),'Draft invoice request');
  await page.goto(`${BASE_URL}/test/fixtures/dashboard-harness.html?tab=agents`);
  await page.getByRole('button',{name:'Connect agent',exact:true}).click();
  await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');
  await page.goto(`${BASE_URL}/test/fixtures/dashboard-harness.html?tab=mandates`);
  await page.getByRole('button',{name:'New permission',exact:true}).click();
  await page.getByRole('heading',{name:'How should payments be approved?'}).waitFor();
  await page.getByRole('button',{name:'Set spending limits'}).click();
  await page.getByRole('heading',{name:'Set your spending limits',exact:true}).waitFor();
  await page.getByRole('textbox',{name:'Max per payment',exact:true}).fill('2.125');
  await page.getByRole('button',{name:'Back',exact:true}).click();
  await page.getByRole('button',{name:'Set spending limits'}).click();
  assert.equal(await page.getByRole('textbox',{name:'Max per payment',exact:true}).inputValue(),'2.125');
  for (const width of [1440,390]) {await page.setViewportSize({width,height:1000});await page.screenshot({path:`/tmp/chainpay-owner-wizard-${width}.png`,fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(`${BASE_URL}/test/fixtures/dashboard-harness.html?tab=mandates&ready`);
  await page.getByRole('button',{name:'New permission',exact:true}).click();
  await page.getByRole('button',{name:'Set spending limits'}).click();
  await page.getByRole('textbox',{name:'Max per payment',exact:true}).fill('2.1250001');
  await page.getByRole('button',{name:'Review permission',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'decimal places'}).waitFor();
  await page.getByRole('textbox',{name:'Max per payment',exact:true}).fill('2.125001');
  await page.getByRole('textbox',{name:'Total spend limit',exact:true}).fill('30.000001');
  await page.getByRole('button',{name:'Review permission',exact:true}).click();
  await page.getByRole('button',{name:'Approve spending permission',exact:true}).waitFor();
  assert.match(await page.locator('.mandate-summary').innerText(),/2\.125001/);
  assert.match(await page.locator('.mandate-summary').innerText(),/30\.000001/);
  await page.screenshot({path:'/tmp/chainpay-owner-review-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Edit spending limits'}).click();
  assert.equal(await page.getByRole('textbox',{name:'Max per payment',exact:true}).inputValue(),'2.125001');
  await page.goto(`${BASE_URL}/test/fixtures/dashboard-harness.html?tab=overview&ready`);
  await page.locator('.wallet-chip').click();
  await page.getByRole('button',{name:'Change account',exact:true}).waitFor();
  await page.waitForTimeout(350);
  await page.screenshot({path:'/tmp/chainpay-owner-wallet-desktop.png'});
  console.log('wallet menu',await page.locator('.wallet-asset-popover').boundingBox());
  await page.keyboard.press('Escape');
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Open dashboard navigation'}).click();
  await page.getByRole('dialog').waitFor();
  await page.keyboard.press('Escape');
  await page.setViewportSize({width:1440,height:1000});
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.evaluate(()=>document.documentElement.style.zoom='2');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:'/tmp/chainpay-owner-zoom.png',fullPage:true});
  await page.evaluate(()=>document.documentElement.style.zoom='1');
  await page.goto(`${BASE_URL}/test/fixtures/dashboard-harness.html?tab=payments&receipts`);
  assert.equal(await page.locator('.receipt-preview-card').count(),0,'history does not auto-open a receipt');
  await page.getByRole('button',{name:/Preview USDC receipt/}).click();
  await page.locator('.receipt-card').waitFor();
  assert.match(await page.locator('.receipt-card-amount').innerText(),/4\.500001/);
  await page.locator('.receipt-lookup > summary').click();
  await page.getByRole('textbox',{name:'Receipt address',exact:true}).fill('invalid address');
  await page.getByRole('button',{name:'Find receipt',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'valid Solana receipt address'}).waitFor();
  await page.getByRole('tab',{name:'Permission + invoice'}).click();
  await page.getByRole('textbox',{name:'Spending permission address'}).fill('11111111111111111111111111111111');
  await page.getByRole('textbox',{name:'Invoice hash'}).fill('abc');
  await page.getByRole('button',{name:'Find receipt',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'64-character'}).waitFor();
  for (const width of [1440,390]) { await page.setViewportSize({width,height:1000}); await page.screenshot({path:`/tmp/chainpay-owner-receipts-${width}.png`,fullPage:true}); assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)); }
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(`${BASE_URL}/test/fixtures/dashboard-harness.html?tab=settings`);
  await page.getByRole('button',{name:'Disconnect',exact:true}).click();
  await page.getByRole('alertdialog').waitFor();await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Revoke all',exact:true}).click();
  await page.getByRole('alertdialog').waitFor();await page.keyboard.press('Escape');
  const toggle=page.getByRole('button',{name:'Collapse navigation'});
  const box=await toggle.boundingBox();assert.ok(Math.abs(box.y+box.height/2-500)<10,'toggle centered vertically');
  await toggle.click();await page.getByRole('button',{name:'Expand navigation'}).click();
  assert.deepEqual(errors,[]);
  console.log('PASS: owner pages, consistent typography, mobile widths, payment history entry, request drafts, connection dialog, permission steps. No financial approval requested.');
} finally {await browser.close();}
