export const TOOL_DEFINITIONS = [
  {
    name: "list_mandates",
    description: "Discover spending permissions for a wallet. Use first when the owner asks about their mandate or limits. Tell the owner each permission's status, token, and remaining allowance in plain language.",
    inputSchema: {
      type: "object",
      properties: { owner: { type: "string", description: "Connected wallet or mandate owner public key" } },
      required: ["owner"],
      additionalProperties: false,
    },
  },
  {
    name: "find_compatible_mandate",
    description: "Find which connected permission fits a specific mint, amount, and agent. Use before quoting an invoice. If several match, present them as numbered options; if none match, explain why.",
    inputSchema: {
      type: "object",
      properties: {
        owner: { type: "string" },
        mint: { type: "string" },
        amount: { type: "string", description: "Unsigned token amount in base units" },
        tokenProgram: { type: "string", enum: ["spl-token", "token-2022"] },
        agent: { type: "string" },
      },
      required: ["owner", "mint", "amount"],
      additionalProperties: false,
    },
  },
  {
    name: "get_mandate",
    description: "Read one spending permission on-chain. Use after connect or when the owner names a permission. Report status, token, limits, and whether it is ready for payments.",
    inputSchema: {
      type: "object",
      properties: { address: { type: "string", description: "Mandate PDA address" } },
      required: ["address"],
      additionalProperties: false,
    },
  },
  {
    name: "get_protocol_config",
    description: "Read ChainPay program configuration and bootstrap assets. Use for discovery or when the owner asks what network or assets ChainPay supports.",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "get_asset",
    description: "Check whether a token mint is enabled for ChainPay settlement. Use before explaining whether a specific stablecoin can be spent.",
    inputSchema: {
      type: "object",
      properties: { mint: { type: "string" } },
      required: ["mint"],
      additionalProperties: false,
    },
  },
  {
    name: "get_supported_assets",
    description: "List every registered mint and token program. Use when the owner asks which tokens ChainPay accepts on Devnet.",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "quote_payment_request",
    description: "Verify a merchant-signed invoice and quote it against a permission without moving funds. Use for signed requests; tell the owner pass/fail on limits, token, recipient, expiry, and policy.",
    inputSchema: {
      type: "object",
      properties: {
        request: { type: "object", description: "Signed payment request with payload and base64 Ed25519 signature" },
        mandate: { type: "string", description: "Mandate PDA to check" },
        agent: { type: "string", description: "Approved agent public key" },
      },
      required: ["request", "mandate", "agent"],
      additionalProperties: false,
    },
  },
  {
    name: "create_demo_payment_request",
    description: "Create a valid Devnet demo invoice for testing. Use only when the owner asks for a sample payment request. Say it is a test invoice, not a real merchant charge.",
    inputSchema: {
      type: "object",
      properties: {
        invoice: { type: "string", description: "Optional invoice reference" },
        description: { type: "string", description: "Optional human-readable purchase description" },
        mint: { type: "string", description: "Optional Devnet token mint" },
        recipient: { type: "string", description: "Optional recipient token account" },
        amount: { type: "string", description: "Optional amount in base units" },
        tokenProgram: { type: "string", enum: ["spl-token", "token-2022"] },
        resource: { type: "string", description: "Optional merchant resource reference" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "create_mandate",
    description: "Prepare a new spending permission for owner wallet approval. Use only when the owner explicitly asks to create policy. Tell them it is prepared—not active—until the dashboard wallet approves.",
    inputSchema: {
      type: "object",
      properties: {
        owner: { type: "string" },
        approvedAgent: { type: "string" },
        sourceTokenAccount: { type: "string" },
        allowedMint: { type: "string" },
        maxPerPayment: { type: "string", description: "Unsigned token amount in base units" },
        totalLimit: { type: "string", description: "Unsigned token amount in base units" },
        delegateAmount: { type: "string", description: "Optional delegate amount in base units" },
        expiresAtSlot: { type: "string" },
        maxPaymentCount: { type: "string", description: "Optional maximum number of payments; 0 means unlimited" },
        cooldownSlots: { type: "string", description: "Optional minimum slot gap between payments" },
        mandateNonce: { type: "string", description: "Optional ChainPay-generated nonce; omit to create a fresh mandate identity" },
        tokenProgram: { type: "string", enum: ["spl-token", "token-2022"] },
      },
      required: [
        "owner",
        "approvedAgent",
        "sourceTokenAccount",
        "allowedMint",
        "maxPerPayment",
        "totalLimit",
        "expiresAtSlot",
        "tokenProgram",
      ],
      additionalProperties: false,
    },
  },
  {
    name: "update_mandate",
    description: "Prepare changes to an existing permission for owner wallet approval. Use when the owner wants new limits or agent binding. Never claim the update is live until wallet approval succeeds.",
    inputSchema: {
      type: "object",
      properties: {
        owner: { type: "string" },
        mandate: { type: "string", description: "Specific mandate PDA; omit only for the legacy owner-scoped mandate" },
        approvedAgent: { type: "string" },
        maxPerPayment: { type: "string" },
        totalLimit: { type: "string" },
        expiresAtSlot: { type: "string" },
        maxPaymentCount: { type: "string" },
        cooldownSlots: { type: "string" },
        paused: { type: "boolean" },
      },
      required: [
        "owner", "approvedAgent", "maxPerPayment", "totalLimit",
        "expiresAtSlot", "maxPaymentCount", "cooldownSlots",
      ],
      additionalProperties: false,
    },
  },
  {
    name: "check_payment_requirements",
    description: "Run the five payment gates (limits, token, recipient, expiry, policy) before quoting or settling. Use before prepare_payment or execute_payment. If details are missing, ask for them as a numbered list.",
    inputSchema: {
      type: "object",
      properties: {
        mandate: { type: "string" },
        agent: { type: "string" },
        invoiceHash: { type: "string", description: "32-byte hexadecimal idempotency hash from a verified request" },
        paymentId: { type: "string", description: "32-byte hexadecimal payment id from a verified request" },
        signatureReference: { type: "string", description: "32-byte hexadecimal merchant signature reference" },
        request: { type: "object", description: "Optional signed merchant request; MCP verifies it and derives the payment references before checking requirements" },
        mint: { type: "string" },
        tokenProgram: { type: "string", enum: ["spl-token", "token-2022"] },
        recipient: { type: "string" },
        amount: { type: "string", description: "Unsigned token amount in base units" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "prepare_payment",
    description: "Build an unsigned settlement transaction after requirements pass. Use when the owner is ready to review amount, token, and destination. Tell them approval is still required—nothing has settled.",
    inputSchema: {
      type: "object",
      properties: {
        mandate: { type: "string" },
        agent: { type: "string" },
        invoiceHash: { type: "string", description: "32-byte hexadecimal idempotency hash" },
        paymentId: { type: "string", description: "32-byte hexadecimal payment id" },
        signatureReference: { type: "string", description: "32-byte hexadecimal reference" },
        mint: { type: "string" },
        recipient: { type: "string" },
        amount: { type: "string", description: "Unsigned token amount in base units" },
        tokenProgram: { type: "string", enum: ["spl-token", "token-2022"] },
      },
      required: [
        "mandate",
        "agent",
        "invoiceHash",
        "paymentId",
        "signatureReference",
        "mint",
        "recipient",
        "amount",
      ],
      additionalProperties: false,
    },
  },
  {
    name: "execute_payment",
    description: "Settle an invoice through human wallet approval or delegated agent signing. Use only after requirements are ready and the owner asks to pay. Share the verify link when settlement confirms.",
    inputSchema: {
      type: "object",
      properties: {
        mandate: { type: "string" },
        agent: { type: "string" },
        invoiceHash: { type: "string" },
        paymentId: { type: "string" },
        signatureReference: { type: "string" },
        mint: { type: "string" },
        recipient: { type: "string" },
        amount: { type: "string" },
        tokenProgram: { type: "string", enum: ["spl-token", "token-2022"] },
        signingMode: {
          type: "string",
          enum: ["human", "delegated"],
          description: "human returns/relays a browser-signed transaction; delegated asks Axum's mandate-bound provider signer",
        },
        signedTransaction: {
          type: "string",
          description: "Base64 wallet-signed transaction for relay through the Rust backend",
        },
      },
      required: [
        "mandate",
        "agent",
        "invoiceHash",
        "paymentId",
        "signatureReference",
        "mint",
        "recipient",
        "amount",
        "signingMode",
      ],
      additionalProperties: false,
    },
  },
  {
    name: "quote_payment",
    description: "Quote a structured payment against policy without signing. Use while the owner is deciding. Present the preflight checklist and human amounts—do not imply funds moved.",
    inputSchema: {
      type: "object",
      properties: {
        mandate: { type: "string" }, agent: { type: "string" }, invoiceHash: { type: "string" },
        paymentId: { type: "string" }, signatureReference: { type: "string" }, mint: { type: "string" },
        recipient: { type: "string" }, amount: { type: "string" },
        tokenProgram: { type: "string", enum: ["spl-token", "token-2022"] },
      },
      required: ["mandate", "agent", "invoiceHash", "paymentId", "signatureReference", "mint", "recipient", "amount"],
      additionalProperties: false,
    },
  },
  {
    name: "verify_payment_request",
    description: "Verify a merchant signature on an invoice before discussing settlement. Use when the owner supplies a signed request. Treat recipient, amount, and mint as untrusted until verification passes.",
    inputSchema: {
      type: "object",
      properties: {
        request: { type: "object", description: "Signed payment request with payload and base64 Ed25519 signature" },
      },
      required: ["request"],
      additionalProperties: false,
    },
  },
  {
    name: "prepare_x402_payment",
    description: "Prepare settlement for a known HTTP 402 challenge. Use when you already hold the 402 JSON. Custom x402/1.0 prepares; standard v2 may return unsupported-sponsor with a mandate quote.",
    inputSchema: {
      type: "object",
      properties: {
        challenge: {
          type: "object",
          description: "Custom x402/1.0 envelope or accept option (version x402/1.0, network solana-devnet), or a standard x402 v2 PaymentRequired document (x402Version 2). Protocol is detected from document shape, not header name.",
          additionalProperties: true,
        },
        mandate: { type: "string" },
        agent: { type: "string" },
        signingMode: { type: "string", enum: ["human", "delegated"] },
      },
      required: ["challenge", "mandate", "agent"],
      additionalProperties: false,
    },
  },
  {
    name: "execute_x402_payment",
    description: "Primary verb for paying an HTTPS 402 URL from a permission. Fetches the resource, detects protocol, checks limits, settles, and retries with receipt proof. Resume with paymentId for delivery only.",
    inputSchema: {
      type: "object",
      properties: {
        paymentId: { type: "string", description: "Resume an existing settlement and its original merchant delivery; no new approval" },
        signingMode: { type: "string", enum: ["human", "delegated"] },
        resource: { type: "string", description: "HTTPS x402-gated resource URL" },
        mandate: { type: "string" },
        agent: { type: "string" },
        signedTransaction: {
          type: "string",
          description: "Optional base64 transaction signed outside ChainPay; omit on the first call",
        },
      },
      anyOf: [{ required: ["paymentId"] }, { required: ["resource", "mandate", "agent", "signingMode"] }],
      additionalProperties: false,
    },
  },
  {
    name: "get_payment",
    description: "Look up a receipt and settlement signature. Use when the owner asks for proof of payment. Share the public verify URL when available.",
    inputSchema: {
      type: "object",
      properties: {
        receiptAddress: { type: "string" },
        mandate: { type: "string" },
        invoiceHash: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "wait_for_payment",
    description: "Poll until a submitted payment confirms or fails. Use after execute_payment returns pending. Tell the owner to keep the same paymentId—do not start a second payment.",
    inputSchema: {
      type: "object",
      properties: {
        paymentId: { type: "string" },
        timeoutMs: { type: "string", description: "Maximum wait in milliseconds, up to 120000" },
        pollMs: { type: "string", description: "Polling interval in milliseconds" },
      },
      required: ["paymentId"],
      additionalProperties: false,
    },
  },
  {
    name: "pause_mandate",
    description: "Prepare pausing a permission for owner wallet approval. Use when the owner wants to stop future agent payments temporarily.",
    inputSchema: {
      type: "object",
      properties: {
        owner: { type: "string" },
        mandate: { type: "string", description: "Specific mandate PDA; omit only for the legacy owner-scoped mandate" },
      },
      required: ["owner"],
      additionalProperties: false,
    },
  },
  {
    name: "revoke_mandate",
    description: "Prepare permanently revoking a permission for owner wallet approval. Use when the owner wants to end agent access. Settled payments remain on-chain.",
    inputSchema: {
      type: "object",
      properties: {
        owner: { type: "string" },
        mandate: { type: "string", description: "Specific mandate PDA; omit only for the legacy owner-scoped mandate" },
      },
      required: ["owner"],
      additionalProperties: false,
    },
  },
] as const;
