export const TOOL_DEFINITIONS = [
  {
    name: "get_mandate",
    description: "Read an on-chain ChainPay payment mandate and its current status.",
    inputSchema: {
      type: "object",
      properties: { address: { type: "string", description: "Mandate PDA address" } },
      required: ["address"],
      additionalProperties: false,
    },
  },
  {
    name: "create_mandate",
    description: "Prepare a wallet-signed mandate creation and limited delegate approval transaction.",
    inputSchema: {
      type: "object",
      properties: {
        owner: { type: "string" },
        approvedAgent: { type: "string" },
        sourceTokenAccount: { type: "string" },
        allowedMint: { type: "string" },
        allowedRecipient: { type: "string" },
        maxPerPayment: { type: "string", description: "Unsigned token amount in base units" },
        totalLimit: { type: "string", description: "Unsigned token amount in base units" },
        delegateAmount: { type: "string", description: "Optional delegate amount in base units" },
        expiresAtSlot: { type: "string" },
        tokenProgram: { type: "string", enum: ["spl-token", "token-2022"] },
      },
      required: [
        "owner",
        "approvedAgent",
        "sourceTokenAccount",
        "allowedMint",
        "allowedRecipient",
        "maxPerPayment",
        "totalLimit",
        "expiresAtSlot",
        "tokenProgram",
      ],
      additionalProperties: false,
    },
  },
  {
    name: "prepare_payment",
    description: "Validate a payment request against the on-chain mandate and prepare an agent-signed transaction.",
    inputSchema: {
      type: "object",
      properties: {
        mandate: { type: "string" },
        agent: { type: "string" },
        invoiceHash: { type: "string", description: "32-byte hexadecimal idempotency hash" },
        paymentId: { type: "string", description: "32-byte hexadecimal payment id" },
        signatureReference: { type: "string", description: "32-byte hexadecimal reference" },
        mint: { type: "string" },
        recipient: { type: "string" },
        amount: { type: "string", description: "Unsigned token amount in base units" },
        tokenProgram: { type: "string", enum: ["spl-token", "token-2022"] },
      },
      required: [
        "mandate",
        "agent",
        "invoiceHash",
        "paymentId",
        "signatureReference",
        "mint",
        "recipient",
        "amount",
      ],
      additionalProperties: false,
    },
  },
  {
    name: "execute_payment",
    description: "Simulate and submit a policy-checked payment through the configured execution adapter.",
    inputSchema: {
      type: "object",
      properties: {
        mandate: { type: "string" },
        agent: { type: "string" },
        invoiceHash: { type: "string" },
        paymentId: { type: "string" },
        signatureReference: { type: "string" },
        mint: { type: "string" },
        recipient: { type: "string" },
        amount: { type: "string" },
        tokenProgram: { type: "string", enum: ["spl-token", "token-2022"] },
      },
      required: [
        "mandate",
        "agent",
        "invoiceHash",
        "paymentId",
        "signatureReference",
        "mint",
        "recipient",
        "amount",
      ],
      additionalProperties: false,
    },
  },
  {
    name: "get_payment",
    description: "Fetch a ChainPay receipt by address or by mandate and invoice hash.",
    inputSchema: {
      type: "object",
      properties: {
        receiptAddress: { type: "string" },
        mandate: { type: "string" },
        invoiceHash: { type: "string" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "pause_mandate",
    description: "Prepare an owner-signed transaction that pauses a ChainPay mandate.",
    inputSchema: {
      type: "object",
      properties: { owner: { type: "string" } },
      required: ["owner"],
      additionalProperties: false,
    },
  },
  {
    name: "revoke_mandate",
    description: "Prepare an owner-signed transaction that permanently revokes a ChainPay mandate.",
    inputSchema: {
      type: "object",
      properties: { owner: { type: "string" } },
      required: ["owner"],
      additionalProperties: false,
    },
  },
] as const;

